menu:
  Home: /
  About Emotional Abuse: /about-emotional-abuse/
  Identify Abuse: /identify-abuse/
  Impact on Children: /impact-on-children/
  Support for Educators: /support-for-educators/
  Children with Special Needs: /children-with-special-needs/
  High Risk Groups: /High-Risk-Groups/
  References: /References/

banner: "images/banner.jpg"